service: team-2-ETL

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  region: eu-west-1
  iam:
    role:
      permissionsBoundary: arn:aws:iam::883232869702:policy/ScopePermissions
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
    layer: true

functions:
  hello:
    handler: handler.hello

package:
  include:
    - src/**
  exclude:
    - "*"
    - "*/**"
  individually: true
  excludeDevDependencies: false
